#!/bin/sh
set -e
package_name=default-jre-8
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/icedtea-netx-javaws.desktop"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/icedtea-netx-javaws.desktop"
;;
esac
exit 0
